version: '3.3'
services:

  foodgram_frontend:
    image: web2cap/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  foodgram_db:
    image: postgres:13.0-alpine
    environment:
        POSTGRES_PASSWORD: mypassword
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  foodgram_web:
    image: web2cap/foodgram_web:latest
    restart: always
    volumes:
      - foodgram_static_value:/app/static/
      - foodgram_media_value:/app/media/
    depends_on:
      - foodgram_db
    env_file:
      - ./.env
  foodgram_nginx:
    image: nginx:1.19.3
    ports:
      - "1080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static_value:/var/html/static/
      - foodgram_media_value:/var/html/media/
    depends_on:
      - foodgram_web

volumes:
  foodgram_static_value:
  foodgram_media_value:
