# Generated by Django 4.1 on 2022-08-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresiens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingerdient",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Ingerdient name"),
        ),
        migrations.AddConstraint(
            model_name="ingerdient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"), name="unique_ingerdient_in_unit"
            ),
        ),
    ]
