# Generated by Django 4.1 on 2022-08-20 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ingrediens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Resipe name")),
                (
                    "image",
                    models.ImageField(
                        upload_to="recipes/images/", verbose_name="Image"
                    ),
                ),
                ("text", models.TextField(verbose_name="Recipe text")),
                (
                    "cooking_time",
                    models.PositiveIntegerField(verbose_name="Cooking time"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resipe",
                "verbose_name_plural": "Resipes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[recipes.validators.validator_not_zero],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "ingredients",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="ingrediens.ingerdient",
                        verbose_name="Ingerdients",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.resipe",
                        verbose_name="Recipe",
                    ),
                ),
            ],
        ),
    ]
