# Generated by Django 4.1 on 2022-08-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipeingredients_ingredients_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredients",
            old_name="ingredients",
            new_name="ingredient",
        ),
    ]
