# Generated by Django 4.1 on 2022-08-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipeingredients_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredients",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="recipes.resipe",
                verbose_name="Recipe",
            ),
        ),
    ]
