# Generated by Django 4.1 on 2022-08-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
        ("recipes", "0003_rename_ingredients_recipeingredients_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingerdients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredients", to="ingredients.ingerdient"
            ),
        ),
    ]
