# Generated by Django 4.1 on 2022-08-21 20:56

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipeingredients_ingredient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Tag name"
                    ),
                ),
                (
                    "colour",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                        unique=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
        ),
    ]
