# Generated by Django 4.1 on 2022-08-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
