# Generated by Django 4.1 on 2022-08-27 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0006_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="favorite",
            field=models.ManyToManyField(
                related_name="favorite_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favorites",
            ),
        ),
    ]
