# Generated by Django 4.1 on 2022-08-27 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_recipe_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="shopping_card",
            field=models.ManyToManyField(
                related_name="shopping_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="In shopping card",
            ),
        ),
    ]
