# Generated by Django 4.1 on 2022-08-28 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0009_alter_recipe_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="shopping_card",
            field=models.ManyToManyField(
                blank=True,
                related_name="shopping_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="In shopping card",
            ),
        ),
    ]
