# Generated by Django 4.1 on 2022-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Publish date"),
        ),
    ]
