# Generated by Django 4.1 on 2022-08-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_alter_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
