# Generated by Django 4.1 on 2022-09-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_alter_recipe_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="colour",
            new_name="color",
        ),
    ]
