# Generated by Django 4.1 on 2022-09-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_alter_recipeingredients_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["-pub_date"], name="recipes_rec_pub_dat_cd8af6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="recipes_tag_slug_3ea026_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="recipes_tag_name_56fd94_idx"),
        ),
    ]
